### ISSUE TITLE
Outdated, non-working installation instructions

### ISSUE THREAD

**Issue by Blaisorblade** [janestreet/janestreet.github.com#25]
[Your installation page](https://janestreet.github.io/installation.html) mentions packages (?) that [you deprecated](https://github.com/ocaml/opam-repository/blob/master/CHANGES.md), such as `bin_prot.syntax` & friends.

```
true: syntax(camlp4o)
true: package(core,sexplib.syntax,bin_prot.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax)
true: thread,debug
```

This leads to errors on a modern install:

```
$ ocamlbuild -use-ocamlfind modulestrongexist.byte
+ ocamlfind ocamldep -package core,sexplib.syntax,bin_prot.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -syntax camlp4o -modules modulestrongexist.ml > modulestrongexist.ml.depends
ocamlfind: Package `sexplib.syntax' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
```

BTW, for whoever cares about the experience of new Ocaml users (not sure where to write this): I'm new around here, but this kind of issues seems common right now — [corebuild was only fixed after the release, and isn't released yet](https://github.com/jmiven/core/commits/e19687cc5ab550d255f744524e282fd971b61203/corebuild), so Real World Ocaml instructions are not working for now, then the old libraries are specifically mentioned in [later chapters](https://realworldocaml.org/v1/en/html/the-compiler-frontend-parsing-and-type-checking.html), etc.
So I spent a couple of hours googling for "missing bin_prot.syntax", assuming I had somehow ended up in an inconsistent package installation state (thanks to my experience with Cabal and Haskell, I have low expectations there).

Again, I don't mean to whine, just help improve docs.

**Comment by diml** [comment]
Sorry about, we'll do a minor release of core and a few other packages today or tomorrow. Currently the replacement instructions on the installation page suffer from another issue which will be fixed as well

**Comment by diml** [comment]
Core and some packages have been updated and should reach opam soon: https://github.com/ocaml/opam-repository/pull/5579

**Comment by Blaisorblade** [comment]
:+1: Thanks for the prompt fix!
